name: DXBConnect
options:
  bundleIdPrefix: com.dxbconnect
  deploymentTarget:
    iOS: "16.0"
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: false

packages:
  DXBCore:
    path: Packages/DXBCore

targets:
  DXBClient:
    type: application
    platform: iOS
    sources:
      - path: Apps/DXBClient
        excludes:
          - "**/*.md"
          - ".next/**"
          - "node_modules/**"
          - "package*.json"
          - "*.config.*"
          - "src/**"
    dependencies:
      - package: DXBCore
    settings:
      base:
        INFOPLIST_FILE: Apps/DXBClient/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.dxbconnect.client
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Apps/DXBClient/Info.plist
      properties:
        CFBundleName: DXB Connect
        CFBundleDisplayName: DXB Connect
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  DXBAdmin:
    type: application
    platform: macOS
    sources:
      - path: Apps/DXBAdmin
        excludes:
          - "**/*.md"
    dependencies:
      - package: DXBCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dxbconnect.admin
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
    info:
      path: Apps/DXBAdmin/Info.plist
      properties:
        CFBundleName: DXB Admin
        CFBundleDisplayName: DXB Admin
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
