name: DXBConnect
options:
  bundleIdPrefix: com.dxbconnect
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  DXBCore:
    path: DXBCore

targets:
  DXBConnect:
    type: application
    platform: iOS
    sources:
      - path: DXBClientApp.swift
      - path: Views
      - path: Assets.xcassets
      - path: Info.plist
        buildPhase: none
      - path: DXBConnect.entitlements
        buildPhase: none
    dependencies:
      - package: DXBCore
      - sdk: PassKit.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dxbconnect.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: DXBConnect.entitlements
        DEVELOPMENT_TEAM: 3CU82K426J
        SWIFT_VERSION: "5.9"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_BITCODE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: NO
    entitlements:
      path: DXBConnect.entitlements
      properties:
        com.apple.developer.in-app-payments:
          - merchant.com.dxbconnect.app
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: DXB Connect
        CFBundleName: DXB Connect
        UILaunchScreen:
          UIColorName: AccentColor
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
