name: DXBConnect
options:
  bundleIdPrefix: com.dxbconnect
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  DXBCore:
    path: DXBCore

targets:
  DXBConnect:
    type: application
    platform: iOS
    sources:
      - path: DXBClientApp.swift
      - path: Views
      - path: Info.plist
        buildPhase: none
    dependencies:
      - package: DXBCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dxbconnect.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Info.plist
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: DXB Connect
        CFBundleName: DXB Connect
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
